<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>
	<ItemGroup>
	  <None Remove="Scripts\Functions\get_week_start_sunday.sql" />
	  <None Remove="Scripts\Views\PayStubHistory.sql" />
	  <None Remove="Scripts\Views\TimesheetHistory.sql" />
	</ItemGroup>
	<ItemGroup>
	  <Content Include="Scripts\Functions\get_week_start_sunday.sql">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Content>
	  <Content Include="Scripts\Views\PayStubHistory.sql">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Content>
	  <Content Include="Scripts\Views\TimesheetHistory.sql">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Content>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Azure.Identity" Version="1.14.0" />
		<PackageReference Include="EFCore.BulkExtensions.PostgreSql" Version="8.1.1" />
		<PackageReference Include="GeoTimeZone" Version="6.1.0" />
		<PackageReference Include="Microsoft.Graph" Version="5.71.0" />
		<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.10" />
		<PackageReference Include="FirebaseAdmin" Version="3.0.1" />
		<PackageReference Include="Microsoft.AspNetCore.DataProtection.EntityFrameworkCore" Version="8.0.11" />
		<PackageReference Include="PdfPig" Version="0.1.15" />
	</ItemGroup>
	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\Covenant.Documents\Covenant.Documents.csproj" />
	</ItemGroup>
</Project>