//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Covenant.Infrastructure {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SqlQueries {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SqlQueries() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Covenant.Infrastructure.SqlQueries", typeof(SqlQueries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string GetNextInvoiceNumber {
            get {
                return ResourceManager.GetString("GetNextInvoiceNumber", resourceCulture);
            }
        }
        
        public static string GetNextInvoiceUSANumber {
            get {
                return ResourceManager.GetString("GetNextInvoiceUSANumber", resourceCulture);
            }
        }
        
        public static string GetNextPayStubNumbers {
            get {
                return ResourceManager.GetString("GetNextPayStubNumbers", resourceCulture);
            }
        }
        
        public static string GetNextPayStubNumbersUSA {
            get {
                return ResourceManager.GetString("GetNextPayStubNumbersUSA", resourceCulture);
            }
        }
        
        public static string PutRequestInProgress {
            get {
                return ResourceManager.GetString("PutRequestInProgress", resourceCulture);
            }
        }
        
        public static string WorkerEarningsHistoryByYear {
            get {
                return ResourceManager.GetString("WorkerEarningsHistoryByYear", resourceCulture);
            }
        }
        
        public static string WorkerEarningsHistoryByMonth {
            get {
                return ResourceManager.GetString("WorkerEarningsHistoryByMonth", resourceCulture);
            }
        }
        
        public static string WorkerEarningsHistoryByWeek {
            get {
                return ResourceManager.GetString("WorkerEarningsHistoryByWeek", resourceCulture);
            }
        }
    }
}
