<Project Sdk="Microsoft.NET.Sdk">

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="Azure.Messaging.ServiceBus" />
	  <PackageReference Include="ClosedXML" />
	  <PackageReference Include="CsvHelper" />
	  <PackageReference Include="FluentValidation" />
	  <PackageReference Include="MediatR" />
	  <PackageReference Include="Microsoft.ApplicationInsights" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Covenant.Infrastructure\Covenant.Infrastructure.csproj" />
	</ItemGroup>

</Project>
