<Project Sdk="Microsoft.NET.Sdk">
    
    <PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
        <IsPackable>false</IsPackable>
        <DefineConstants>$(RUN_BAMBORA)</DefineConstants>
        <UserSecretsId>6f9fc3c1-578a-490d-a3c0-e9afb502fc69</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <Using Include="System.Net.Http.Json" />
        <Using Include="Microsoft.AspNetCore.Builder" />
        <Using Include="Microsoft.AspNetCore.Hosting" />
        <Using Include="Microsoft.AspNetCore.Http" />
        <Using Include="Microsoft.AspNetCore.Routing" />
        <Using Include="Microsoft.Extensions.Configuration" />
        <Using Include="Microsoft.Extensions.DependencyInjection" />
        <Using Include="Microsoft.Extensions.Hosting" />
        <Using Include="Microsoft.Extensions.Logging" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" />
        <PackageReference Include="xunit.runner.visualstudio">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Moq" />
        <PackageReference Include="xunit" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Covenant.Api\Covenant.Api.csproj" />
    </ItemGroup>

    <ItemGroup>
      <None Update="AgencyModule\AgencyInvoicePaymentSupport\invoiceSupport.txt">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="AgencyModule\AgencyInvoicePaymentSupport\invoiceSupport.pdf">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Common\cpp_weekly.xlsx">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Files\some_pay_stub.pdf">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Common\imageprofile.jpg">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
        <None Update="Common\imageprofilelarge.jpg">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="Common\imageprofile.invalidformat">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="Common\social_insurance_test.pdf">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="Common\resume_test.pdf">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="Common\Fake_Invoice.pdf">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="Files\some_invoice.pdf">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="Common\cpp_biweekly.xlsx">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="Common\cpp_semi_monthly.xlsx">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="Common\cpp_monthly.xlsx">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="Common\fake_paystub.pdf">
          <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="Common\fake_paystub.html">
          <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="Common\fake_paystub_usa.html">
          <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="Common\fake_invoice.html">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="Common\fake_invoice_usa.html">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
    </ItemGroup>

    <ItemGroup>
      <None Update="Common\appsettings.test.json">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="appsettings.json">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
    </ItemGroup>

</Project>
