using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Covenant.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class AddSourceCatalogTable : Migration
    {
        // Catalog values seeded on creation. Ids are generated by the database (gen_random_uuid()).
        private static readonly string[] SeedSources =
        {
            "Indeed",
            "Zip Recruiter",
            "Linkedin",
            "Referred",
            "Sigook",
            "Covenant",
            "Other",
        };

        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // 1. Create the catalog table (Id is generated by the database) and seed it.
            migrationBuilder.CreateTable(
                name: "Sources",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uuid", nullable: false, defaultValueSql: "gen_random_uuid()"),
                    Value = table.Column<string>(type: "text", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Sources", x => x.Id);
                });

            migrationBuilder.CreateIndex(
                name: "IX_Sources_Value",
                table: "Sources",
                column: "Value",
                unique: true);

            foreach (var value in SeedSources)
            {
                migrationBuilder.Sql($"INSERT INTO \"Sources\" (\"Value\") VALUES ('{value}');");
            }

            // 2. Add the FK column to Candidates.
            migrationBuilder.AddColumn<Guid>(
                name: "SourceId",
                table: "Candidates",
                type: "uuid",
                nullable: true);

            // 3. Migrate existing data: match the old text against the catalog (case-insensitive);
            //    anything that does not match is catalogued as "Other".
            migrationBuilder.Sql(
                "UPDATE \"Candidates\" c " +
                "SET \"SourceId\" = s.\"Id\" " +
                "FROM \"Sources\" s " +
                "WHERE LOWER(TRIM(c.\"Source\")) = LOWER(s.\"Value\");");

            // Legacy combined value "Covenant|Sigook" is catalogued as "Sigook".
            migrationBuilder.Sql(
                "UPDATE \"Candidates\" " +
                "SET \"SourceId\" = (SELECT \"Id\" FROM \"Sources\" WHERE \"Value\" = 'Sigook') " +
                "WHERE \"SourceId\" IS NULL AND LOWER(TRIM(\"Source\")) = 'covenant|sigook';");

            migrationBuilder.Sql(
                "UPDATE \"Candidates\" " +
                "SET \"SourceId\" = (SELECT \"Id\" FROM \"Sources\" WHERE \"Value\" = 'Other') " +
                "WHERE \"SourceId\" IS NULL;");

            // 4. Drop the legacy text column.
            migrationBuilder.DropColumn(
                name: "Source",
                table: "Candidates");

            // 5. Wire up the relationship.
            migrationBuilder.CreateIndex(
                name: "IX_Candidates_SourceId",
                table: "Candidates",
                column: "SourceId");

            migrationBuilder.AddForeignKey(
                name: "FK_Candidates_Sources_SourceId",
                table: "Candidates",
                column: "SourceId",
                principalTable: "Sources",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<string>(
                name: "Source",
                table: "Candidates",
                type: "text",
                nullable: true);

            // Restore the text value from the catalog before dropping the relationship.
            migrationBuilder.Sql(
                "UPDATE \"Candidates\" c " +
                "SET \"Source\" = s.\"Value\" " +
                "FROM \"Sources\" s " +
                "WHERE c.\"SourceId\" = s.\"Id\";");

            migrationBuilder.DropForeignKey(
                name: "FK_Candidates_Sources_SourceId",
                table: "Candidates");

            migrationBuilder.DropIndex(
                name: "IX_Candidates_SourceId",
                table: "Candidates");

            migrationBuilder.DropColumn(
                name: "SourceId",
                table: "Candidates");

            migrationBuilder.DropTable(
                name: "Sources");
        }
    }
}
