<template>
  <div class="disclaimer-page">
    <MainNavbar />
    <div class="disclaimer-container">
      <div class="disclaimer-content">
        <h1 class="disclaimer-title">DISCLAIMER</h1>
        <div class="disclaimer-text">
          <p>
            YOU UNDERSTAND AND AGREE THAT YOUR USE OF THE COVENANT GROUP LTD. WEBSITE, THE SOFTWARE, RUNNING EITHER ON A MOBILE OR DESKTOP (COLLECTIVELY, "<strong>COVENANT GROUP</strong>"), ITS CONTENT, AND ANY SERVICES OR ITEMS FOUND OR ATTAINED THROUGH COVENANT GROUP IS AT YOUR OWN RISK. COVENANT GROUP, ITS CONTENT, AND ANY SERVICES OR ITEMS FOUND OR ATTAINED THROUGH COVENANT GROUP ARE PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS, WITHOUT ANY WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT. THE FOREGOING DOES NOT AFFECT ANY WARRANTIES THAT CANNOT BE EXCLUDED OR LIMITED UNDER APPLICABLE LAW.
          </p>

          <p>
            NEITHER COVENANT GROUP LTD. (THE "<strong>COMPANY</strong>") NOR ITS PARENT, SUBSIDIARIES, AFFILIATES OR THEIR RESPECTIVE DIRECTORS, OFFICERS, EMPLOYEES, AGENTS, SERVICE PROVIDERS, CONTRACTORS, LICENSORS, LICENSEES, SUPPLIERS OR SUCCESSORS MAKE ANY WARRANTY, REPRESENTATION OR ENDORSEMENT WITH RESPECT TO THE COMPLETENESS, SECURITY, RELIABILITY, SUITABILITY, ACCURACY, CURRENCY OR AVAILABILITY OF COVENANT GROUP OR ITS CONTENTS. WITHOUT LIMITING THE FOREGOING, NEITHER THE COMPANY NOR ITS PARENT, SUBSIDIARIES, AFFILIATES OR THEIR RESPECTIVE DIRECTORS, OFFICERS, EMPLOYEES, AGENTS, SERVICE PROVIDERS, CONTRACTORS, LICENSORS, LICENSEES, SUPPLIERS OR SUCCESSORS REPRESENT OR WARRANT THAT COVENANT GROUP, ITS CONTENT, OR ANY SERVICES OR ITEMS FOUND OR ATTAINED THROUGH COVENANT GROUP WILL BE ACCURATE, RELIABLE, ERROR-FREE, OR UNINTERRUPTED, THAT DEFECTS WILL BE CORRECTED, THAT COVENANT GROUP OR THE SERVER THAT MAKES IT AVAILABLE ARE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS.
          </p>

          <p>
            WE CANNOT AND DO NOT GUARANTEE OR WARRANT THAT FILES OR DATA AVAILABLE FOR DOWNLOADING FROM THE INTERNET OR COVENANT GROUP WILL BE FREE OF VIRUSES OR OTHER DESTRUCTIVE CODE. YOU ARE SOLELY AND ENTIRELY RESPONSIBLE FOR YOUR USE OF COVENANT GROUP AND YOUR COMPUTER, MOBILE, INTERNET AND DATA SECURITY. TO THE FULLEST EXTENT PROVIDED BY LAW, WE WILL NOT BE LIABLE FOR ANY LOSS OR DAMAGE CAUSED BY DENIAL-OF-SERVICE ATTACK, DISTRIBUTED DENIAL-OF-SERVICE ATTACK, OVERLOADING, FLOODING, MAILBOMBING OR CRASHING, VIRUSES, TROJAN HORSES, WORMS, LOGIC BOMBS, OR OTHER TECHNOLOGICALLY HARMFUL MATERIAL THAT MAY INFECT YOUR COMPUTER EQUIPMENT, COMPUTER PROGRAMS, DATA, OR OTHER PROPRIETARY MATERIAL DUE TO YOUR USE OF COVENANT GROUP OR ANY SERVICES OR ITEMS FOUND OR ATTAINED THROUGH COVENANT GROUP OR TO YOUR DOWNLOADING OF ANY MATERIAL POSTED ON IT, OR ON ANY WEBSITE OR APPLICATION LINKED TO IT.
          </p>

          <p>
            EXCEPT WHERE SUCH EXCLUSIONS ARE PROHIBITED BY LAW, UNDER NO CIRCUMSTANCE WILL THE COMPANY NOR ITS PARENT, SUBSIDIARIES, AFFILIATES OR THEIR RESPECTIVE DIRECTORS, OFFICERS, EMPLOYEES, AGENTS, SERVICE PROVIDERS, CONTRACTORS, LICENSORS, LICENSEES, SUPPLIERS, OR SUCCESSORS BE LIABLE FOR NEGLIGENCE, GROSS NEGLIGENCE, NEGLIGENT MISREPRESENTATION, FUNDAMENTAL BREACH, DAMAGES OF ANY KIND, UNDER ANY LEGAL THEORY, INCLUDING ANY DIRECT, INDIRECT, SPECIAL, INCIDENTAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING, BUT NOT LIMITED TO, PERSONAL INJURY, PAIN AND SUFFERING, EMOTIONAL DISTRESS, LOSS OF REVENUE, LOSS OF PROFITS, LOSS OF BUSINESS OR ANTICIPATED SAVINGS, LOSS OF USE, LOSS OF GOODWILL, LOSS OF DATA, AND WHETHER CAUSED BY TORT (INCLUDING NEGLIGENCE), BREACH OF CONTRACT, BREACH OF PRIVACY OR OTHERWISE, EVEN IF THE PARTY WAS ALLEGEDLY ADVISED OR HAD REASON TO KNOW, ARISING OUT OF OR IN CONNECTION WITH YOUR USE, OR INABILITY TO USE, OR RELIANCE ON, COVENANT GROUP, ANY LINKED WEBSITES OR APPLICATIONS OR SUCH OTHER THIRD-PARTY WEBSITES OR APPLICATIONS, NOR ANY CONTENT, MATERIALS, POSTING OR INFORMATION THEREON EVEN IF THE PARTY WAS ALLEGEDLY ADVISED OR HAD REASON TO KNOW.
          </p>

          <h2>ADDITIONAL DISCLAIMERS REGARDING SERVICES, APPLICATIONS, AND THIRD-PARTY SYSTEMS</h2>

          <p>
            WITHOUT LIMITING THE FOREGOING, YOU FURTHER ACKNOWLEDGE AND AGREE THAT COVENANT GROUP LTD., TOGETHER WITH ITS AFFILIATES, RELATED ENTITIES, AND PARTNERS, INCLUDING BUT NOT LIMITED TO SIGOOK (COLLECTIVELY, "COVENANT GROUP"), MAY PROVIDE STAFFING, RECRUITMENT (INCLUDING TEMPORARY AND PERMANENT PLACEMENT), AND WORKFORCE-RELATED SERVICES THROUGH WEBSITES, MOBILE APPLICATIONS, AND THIRD-PARTY OR AFFILIATED SYSTEMS (COLLECTIVELY, THE "PLATFORMS").
          </p>

          <p>
            COVENANT GROUP DOES NOT GUARANTEE EMPLOYMENT, JOB PLACEMENT, CONTINUITY OF WORK, OR ANY PARTICULAR OUTCOME ARISING FROM THE USE OF THE PLATFORMS OR SERVICES. ALL HIRING DECISIONS ARE MADE SOLELY BY EMPLOYERS, AND ANY INDIVIDUAL HIRED PURSUANT TO A PERMANENT OR TEMPORARY PLACEMENT SHALL BE DEEMED AN EMPLOYEE OF THE HIRING EMPLOYER ONLY. COVENANT GROUP SHALL NOT BE RESPONSIBLE OR LIABLE FOR THE ACTIONS, OMISSIONS, DECISIONS, OR EMPLOYMENT PRACTICES OF ANY EMPLOYER OR CLIENT.
          </p>

          <p>
            YOU FURTHER ACKNOWLEDGE THAT THE AVAILABILITY, FUNCTIONALITY, AND ACCURACY OF THE PLATFORMS MAY BE AFFECTED BY FACTORS OUTSIDE OF COVENANT GROUP'S CONTROL, INCLUDING BUT NOT LIMITED TO INTERNET CONNECTIVITY, MOBILE NETWORK COVERAGE, DEVICE TYPE, OPERATING SYSTEM, USER SETTINGS, AND GEOGRAPHIC LOCATION. LOCATION-BASED, TIME-TRACKING, OR SIMILAR FEATURES MAY NOT BE PRECISE OR CONTINUOUS IN ALL LOCATIONS OR CIRCUMSTANCES. TO THE FULLEST EXTENT PERMITTED BY LAW, COVENANT GROUP DISCLAIMS ANY LIABILITY ARISING FROM SUCH LIMITATIONS OR INACCURACIES.
          </p>

          <p>
            ANY REPLACEMENT PERIODS, GUARANTEES, OR SIMILAR COMMERCIAL TERMS THAT MAY BE OFFERED IN CONNECTION WITH RECRUITMENT OR PLACEMENT SERVICES SHALL APPLY ONLY IF AND TO THE EXTENT EXPRESSLY SET OUT IN A SEPARATE WRITTEN AGREEMENT BETWEEN COVENANT GROUP AND THE APPLICABLE CLIENT, AND SHALL NOT BE IMPLIED, INCORPORATED, OR CREATED BY THIS DISCLAIMER.
          </p>
        </div>
      </div>
    </div>
    <MainFooter />
  </div>
</template>

<script setup lang="ts">
import { useSeoMeta } from '@unhead/vue'
import MainNavbar from '@/components/layout/MainNavbar.vue'
import MainFooter from '@/components/layout/MainFooter.vue'

useSeoMeta({
  title: 'Disclaimer - Covenant Group',
  description: 'Read the disclaimer for Covenant Group services, website, and applications including terms of use and liability limitations.',
  ogTitle: 'Disclaimer - Covenant Group',
  ogDescription: 'Disclaimer for Covenant Group services, website, and applications.',
})
</script>

<style scoped>
.disclaimer-page {
  min-height: 100vh;
  background-color: #f5f5f5;
  margin: 0;
  padding: 0;
}

.disclaimer-container {
  max-width: 1200px;
  margin: 0 auto;
  padding: 80px 40px;
}

.disclaimer-content {
  background: #ffffff;
  border-radius: 12px;
  padding: 60px;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);
}

.disclaimer-title {
  font-size: 2.5rem;
  font-weight: 700;
  color: #0F2F44;
  margin-bottom: 40px;
  font-family: Poppins, sans-serif;
}

.disclaimer-text {
  color: #333333;
  font-size: 1rem;
  line-height: 1.8;
  font-family: Poppins, sans-serif;
}

.disclaimer-text h2 {
  font-size: 1.5rem;
  font-weight: 600;
  color: #0F2F44;
  margin-top: 32px;
  margin-bottom: 16px;
}

.disclaimer-text h3 {
  font-size: 1.25rem;
  font-weight: 600;
  color: #0F2F44;
  margin-top: 24px;
  margin-bottom: 12px;
}

.disclaimer-text p {
  margin-bottom: 16px;
}

.disclaimer-text ul,
.disclaimer-text ol {
  margin-left: 24px;
  margin-bottom: 16px;
}

.disclaimer-text li {
  margin-bottom: 8px;
}

.disclaimer-text strong {
  font-weight: 600;
  color: #0F2F44;
}

/* Responsive */
@media (max-width: 768px) {
  .disclaimer-container {
    padding: 60px 24px;
  }

  .disclaimer-content {
    padding: 40px 24px;
  }

  .disclaimer-title {
    font-size: 2rem;
  }

  .disclaimer-text {
    font-size: 0.95rem;
  }
}

@media (max-width: 480px) {
  .disclaimer-container {
    padding: 40px 16px;
  }

  .disclaimer-content {
    padding: 32px 20px;
  }

  .disclaimer-title {
    font-size: 1.75rem;
  }
}
</style>
