<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<IsPackable>False</IsPackable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="CsvHelper" />
		<PackageReference Include="FluentValidation" />
		<PackageReference Include="libphonenumber-csharp" />
		<PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" />
	</ItemGroup>

	<ItemGroup>
		<Compile Update="Resources\ApiResources.Designer.cs">
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
			<DependentUpon>ApiResources.resx</DependentUpon>
		</Compile>
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Update="Resources\ApiResources.es.resx">
			<Generator></Generator>
		</EmbeddedResource>
		<EmbeddedResource Update="Resources\ApiResources.resx">
			<Generator>PublicResXFileCodeGenerator</Generator>
			<LastGenOutput>ApiResources.Designer.cs</LastGenOutput>
		</EmbeddedResource>
	</ItemGroup>

</Project>
