//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Covenant.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ApiResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApiResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Covenant.Common.Resources.ApiResources", typeof(ApiResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Items.
        /// </summary>
        public static string AdditionalItems {
            get {
                return ResourceManager.GetString("AdditionalItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agency.
        /// </summary>
        public static string Agency {
            get {
                return ResourceManager.GetString("Agency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You already have an account with this email.
        /// </summary>
        public static string AgencyAlreadyExist {
            get {
                return ResourceManager.GetString("AgencyAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This worker is an a request with the same work shift please try another one ({0}).
        /// </summary>
        public static string AgencyBookWorkerWithSameWorkShift {
            get {
                return ResourceManager.GetString("AgencyBookWorkerWithSameWorkShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agency not found.
        /// </summary>
        public static string AgencyNotFound {
            get {
                return ResourceManager.GetString("AgencyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved Hours.
        /// </summary>
        public static string ApprovedHours {
            get {
                return ResourceManager.GetString("ApprovedHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asap Rate.
        /// </summary>
        public static string AsapRate {
            get {
                return ResourceManager.GetString("AsapRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Availabilities.
        /// </summary>
        public static string Availabilities {
            get {
                return ResourceManager.GetString("Availabilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AvailabilityDays.
        /// </summary>
        public static string AvailabilityDays {
            get {
                return ResourceManager.GetString("AvailabilityDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AvailabilityTimes.
        /// </summary>
        public static string AvailabilityTimes {
            get {
                return ResourceManager.GetString("AvailabilityTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Information.
        /// </summary>
        public static string BillingInformation {
            get {
                return ResourceManager.GetString("BillingInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Location.
        /// </summary>
        public static string BillingLocation {
            get {
                return ResourceManager.GetString("BillingLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BirthDay.
        /// </summary>
        public static string BirthDay {
            get {
                return ResourceManager.GetString("BirthDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business name.
        /// </summary>
        public static string BusinessName {
            get {
                return ResourceManager.GetString("BusinessName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Number.
        /// </summary>
        public static string BusinessNumber {
            get {
                return ResourceManager.GetString("BusinessNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificates.
        /// </summary>
        public static string Certificates {
            get {
                return ResourceManager.GetString("Certificates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City Of Incorporation.
        /// </summary>
        public static string CityOfIncorporation {
            get {
                return ResourceManager.GetString("CityOfIncorporation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A company with this email {0} already exists.
        /// </summary>
        public static string CompanyAlreadyExist {
            get {
                return ResourceManager.GetString("CompanyAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This worker is in a request with the same work shift please try changing the work shift ({0}).
        /// </summary>
        public static string CompanyBookWorkerWithSameWorkShift {
            get {
                return ResourceManager.GetString("CompanyBookWorkerWithSameWorkShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company name.
        /// </summary>
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Emergency FirstName.
        /// </summary>
        public static string ContactEmergencyLastName {
            get {
                return ResourceManager.GetString("ContactEmergencyLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Emergency FirstName.
        /// </summary>
        public static string ContactEmergencyName {
            get {
                return ResourceManager.GetString("ContactEmergencyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Emergency Phone.
        /// </summary>
        public static string ContactEmergencyPhone {
            get {
                return ResourceManager.GetString("ContactEmergencyPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Information.
        /// </summary>
        public static string ContactInformation {
            get {
                return ResourceManager.GetString("ContactInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Persons.
        /// </summary>
        public static string ContactPersons {
            get {
                return ResourceManager.GetString("ContactPersons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Of Incorporation.
        /// </summary>
        public static string DateOfIncorporation {
            get {
                return ResourceManager.GetString("DateOfIncorporation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days.
        /// </summary>
        public static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Deductions.
        /// </summary>
        public static string DeductionsOther {
            get {
                return ResourceManager.GetString("DeductionsOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discounts.
        /// </summary>
        public static string Discounts {
            get {
                return ResourceManager.GetString("Discounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DueDate.
        /// </summary>
        public static string DueDate {
            get {
                return ResourceManager.GetString("DueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration Break.
        /// </summary>
        public static string DurationBreak {
            get {
                return ResourceManager.GetString("DurationBreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duties.
        /// </summary>
        public static string Duties {
            get {
                return ResourceManager.GetString("Duties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email address is already taken. Please choose another one..
        /// </summary>
        public static string EmailAlreadyTaken {
            get {
                return ResourceManager.GetString("EmailAlreadyTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmergencyPhone.
        /// </summary>
        public static string EmergencyPhone {
            get {
                return ResourceManager.GetString("EmergencyPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error sending notification.
        /// </summary>
        public static string ErrorSendingNotification {
            get {
                return ResourceManager.GetString("ErrorSendingNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of days can not be less than the number of days elapsed of the request.
        /// </summary>
        public static string ErrorUpdateRequestDays {
            get {
                return ResourceManager.GetString("ErrorUpdateRequestDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El número de trabajadores no puede ser inferior al número de trabajadores que aplicarón si desea puede rechazar alguno de ellos del listado de trabajadores.
        /// </summary>
        public static string ErrorUpdateWorkersQuantity {
            get {
                return ResourceManager.GetString("ErrorUpdateWorkersQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FareOrExtras.
        /// </summary>
        public static string FareOrExtras {
            get {
                return ResourceManager.GetString("FareOrExtras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        public static string Fax {
            get {
                return ResourceManager.GetString("Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Day.
        /// </summary>
        public static string FirstDay {
            get {
                return ResourceManager.GetString("FirstDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First FirstName.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full FirstName.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred please try again, if the error persists try later one of our engineers will solve it soon.
        /// </summary>
        public static string GeneralError {
            get {
                return ResourceManager.GetString("GeneralError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health Problem.
        /// </summary>
        public static string HealthProblem {
            get {
                return ResourceManager.GetString("HealthProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hour Price.
        /// </summary>
        public static string HourPrice {
            get {
                return ResourceManager.GetString("HourPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours Day.
        /// </summary>
        public static string HoursDay {
            get {
                return ResourceManager.GetString("HoursDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HST #.
        /// </summary>
        public static string HstNumber {
            get {
                return ResourceManager.GetString("HstNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identification Number.
        /// </summary>
        public static string IdentificationNumber1 {
            get {
                return ResourceManager.GetString("IdentificationNumber1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identification Number.
        /// </summary>
        public static string IdentificationNumber2 {
            get {
                return ResourceManager.GetString("IdentificationNumber2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The identification number {0} is already taken. Please choose another one..
        /// </summary>
        public static string IdentificationNumberAlreadyTaken {
            get {
                return ResourceManager.GetString("IdentificationNumberAlreadyTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identification Type One.
        /// </summary>
        public static string IdentificationType1 {
            get {
                return ResourceManager.GetString("IdentificationType1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identification Type Two.
        /// </summary>
        public static string IdentificationType2 {
            get {
                return ResourceManager.GetString("IdentificationType2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incentive.
        /// </summary>
        public static string Incentive {
            get {
                return ResourceManager.GetString("Incentive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incentive Description.
        /// </summary>
        public static string IncentiveDescription {
            get {
                return ResourceManager.GetString("IncentiveDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; must be between {1} and {2}. You entered {3}..
        /// </summary>
        public static string InclusiveBetweenValidator {
            get {
                return ResourceManager.GetString("InclusiveBetweenValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{PropertyName}&apos; must be between {From} and {To}. You entered {Value}..
        /// </summary>
        public static string InclusiveBetweenValidator2 {
            get {
                return ResourceManager.GetString("InclusiveBetweenValidator2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Industry.
        /// </summary>
        public static string Industry {
            get {
                return ResourceManager.GetString("Industry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid job position.
        /// </summary>
        public static string InvalidJobPosition {
            get {
                return ResourceManager.GetString("InvalidJobPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Request.
        /// </summary>
        public static string InvalidRequest {
            get {
                return ResourceManager.GetString("InvalidRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The URL format isn&apos;t valid .
        /// </summary>
        public static string InvalidWebPage {
            get {
                return ResourceManager.GetString("InvalidWebPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Experiences.
        /// </summary>
        public static string JobExperiences {
            get {
                return ResourceManager.GetString("JobExperiences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Location.
        /// </summary>
        public static string JobLocation {
            get {
                return ResourceManager.GetString("JobLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Position.
        /// </summary>
        public static string JobPosition {
            get {
                return ResourceManager.GetString("JobPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Position Rates.
        /// </summary>
        public static string JobPositionRates {
            get {
                return ResourceManager.GetString("JobPositionRates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Title.
        /// </summary>
        public static string JobTitle {
            get {
                return ResourceManager.GetString("JobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages.
        /// </summary>
        public static string Languages {
            get {
                return ResourceManager.GetString("Languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License File.
        /// </summary>
        public static string LicenseFile {
            get {
                return ResourceManager.GetString("LicenseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licenses.
        /// </summary>
        public static string Licenses {
            get {
                return ResourceManager.GetString("Licenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lift.
        /// </summary>
        public static string Lift {
            get {
                return ResourceManager.GetString("Lift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Preferences.
        /// </summary>
        public static string LocationPreferences {
            get {
                return ResourceManager.GetString("LocationPreferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locations.
        /// </summary>
        public static string Locations {
            get {
                return ResourceManager.GetString("Locations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo.
        /// </summary>
        public static string Logo {
            get {
                return ResourceManager.GetString("Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This file can&apos;t be uploaded, because it exceeds the maximum file-size 10MB.
        /// </summary>
        public static string MaxSizeFileError {
            get {
                return ResourceManager.GetString("MaxSizeFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyFirstName} must be greater than or equal to {ComparisonValue}..
        /// </summary>
        public static string MEGreaterThanOrEqualTo {
            get {
                return ResourceManager.GetString("MEGreaterThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyFirstName} is incomplete.
        /// </summary>
        public static string MEIncomplete {
            get {
                return ResourceManager.GetString("MEIncomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The rating must be between 0 and 5.
        /// </summary>
        public static string MEInvalidCommentRate {
            get {
                return ResourceManager.GetString("MEInvalidCommentRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address is not valid.
        /// </summary>
        public static string MEInvalidEmail {
            get {
                return ResourceManager.GetString("MEInvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{PropertyName}&apos; is not valid..
        /// </summary>
        public static string MEInvalidEndDate {
            get {
                return ResourceManager.GetString("MEInvalidEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Job Rate.
        /// </summary>
        public static string MEInvalidJobRate {
            get {
                return ResourceManager.GetString("MEInvalidJobRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The logo is invalid.
        /// </summary>
        public static string MEInvalidLogo {
            get {
                return ResourceManager.GetString("MEInvalidLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyFirstName} must be less than or equal to {ComparisonValue}..
        /// </summary>
        public static string MELessThanOrEqualTo {
            get {
                return ResourceManager.GetString("MELessThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one.
        /// </summary>
        public static string MEListAny {
            get {
                return ResourceManager.GetString("MEListAny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length of {PropertyFirstName} must be {MaxLength} characters or fewer. You entered {TotalLength} characters..
        /// </summary>
        public static string MEMaxLegth {
            get {
                return ResourceManager.GetString("MEMaxLegth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length of {PropertyFirstName} must be at least {MinLength} characters. You entered {TotalLength} characters..
        /// </summary>
        public static string MEMinLegth {
            get {
                return ResourceManager.GetString("MEMinLegth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyFirstName} should not be empty..
        /// </summary>
        public static string MENotEmpty {
            get {
                return ResourceManager.GetString("MENotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{PropertyName}&apos; should not be empty..
        /// </summary>
        public static string MERequiredField {
            get {
                return ResourceManager.GetString("MERequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle Name.
        /// </summary>
        public static string MiddleName {
            get {
                return ResourceManager.GetString("MiddleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Hours.
        /// </summary>
        public static string MissingHours {
            get {
                return ResourceManager.GetString("MissingHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Hours Overtime.
        /// </summary>
        public static string MissingHoursOvertime {
            get {
                return ResourceManager.GetString("MissingHoursOvertime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Number.
        /// </summary>
        public static string MobileNumber {
            get {
                return ResourceManager.GetString("MobileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At this time there is no agency available.
        /// </summary>
        public static string NotAgencyAvailable {
            get {
                return ResourceManager.GetString("NotAgencyAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of workers is complete..
        /// </summary>
        public static string NumberOfWorkersComplete {
            get {
                return ResourceManager.GetString("NumberOfWorkersComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office Number.
        /// </summary>
        public static string OfficeNumber {
            get {
                return ResourceManager.GetString("OfficeNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Test.
        /// </summary>
        public static string OrderTest {
            get {
                return ResourceManager.GetString("OrderTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Health Problem.
        /// </summary>
        public static string OtherHealthProblem {
            get {
                return ResourceManager.GetString("OtherHealthProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PayStub cannot be created if worker is subcontractor.
        /// </summary>
        public static string PayStub_cannot_be_created_if_worker_is_subcontractor {
            get {
                return ResourceManager.GetString("PayStub_cannot_be_created_if_worker_is_subcontractor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description is required.
        /// </summary>
        public static string PayStubItemDescriptionRequired {
            get {
                return ResourceManager.GetString("PayStubItemDescriptionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Alternate.
        /// </summary>
        public static string PhoneAlternate {
            get {
                return ResourceManager.GetString("PhoneAlternate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ext..
        /// </summary>
        public static string PhoneExt {
            get {
                return ResourceManager.GetString("PhoneExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Principal.
        /// </summary>
        public static string PhonePrincipal {
            get {
                return ResourceManager.GetString("PhonePrincipal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Your current subscription only allow to book {0} workers&quot;.
        /// </summary>
        public static string PlanCompanyErrorMaximumBookWorkers {
            get {
                return ResourceManager.GetString("PlanCompanyErrorMaximumBookWorkers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Police Check/BackGround.
        /// </summary>
        public static string PoliceCheckBackGround {
            get {
                return ResourceManager.GetString("PoliceCheckBackGround", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code.
        /// </summary>
        public static string PostalCode {
            get {
                return ResourceManager.GetString("PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Image.
        /// </summary>
        public static string ProfileImage {
            get {
                return ResourceManager.GetString("ProfileImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate.
        /// </summary>
        public static string Rate {
            get {
                return ResourceManager.GetString("Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat.
        /// </summary>
        public static string Repeat {
            get {
                return ResourceManager.GetString("Repeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request has finished.
        /// </summary>
        public static string RequestHasFinished {
            get {
                return ResourceManager.GetString("RequestHasFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This order isn&apos;t available.
        /// </summary>
        public static string RequestNotAvailable {
            get {
                return ResourceManager.GetString("RequestNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requirements.
        /// </summary>
        public static string Requirements {
            get {
                return ResourceManager.GetString("Requirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second Last Name.
        /// </summary>
        public static string SecondLastName {
            get {
                return ResourceManager.GetString("SecondLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sigook™.
        /// </summary>
        public static string SigookCapitalize {
            get {
                return ResourceManager.GetString("SigookCapitalize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIGOOK™.
        /// </summary>
        public static string SigookUpper {
            get {
                return ResourceManager.GetString("SigookUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skills.
        /// </summary>
        public static string Skills {
            get {
                return ResourceManager.GetString("Skills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social Insurance.
        /// </summary>
        public static string SocialInsurance {
            get {
                return ResourceManager.GetString("SocialInsurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The social insurance is already taken. Please choose another one..
        /// </summary>
        public static string SocialInsuranceAlreadyTaken {
            get {
                return ResourceManager.GetString("SocialInsuranceAlreadyTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social Insurance Date.
        /// </summary>
        public static string SocialInsuranceDate {
            get {
                return ResourceManager.GetString("SocialInsuranceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social Insurance File.
        /// </summary>
        public static string SocialInsuranceFile {
            get {
                return ResourceManager.GetString("SocialInsuranceFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supervisor.
        /// </summary>
        public static string Supervisor {
            get {
                return ResourceManager.GetString("Supervisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is not enough information to generate a pay stub.
        /// </summary>
        public static string There_is_not_enough_information_to_generate_pay_stub {
            get {
                return ResourceManager.GetString("There_is_not_enough_information_to_generate_pay_stub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time End Night Shift.
        /// </summary>
        public static string TimeEndNightShift {
            get {
                return ResourceManager.GetString("TimeEndNightShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timesheet currently used in an invoice please, first delete the invoice..
        /// </summary>
        public static string TimeSheetRepository_DeleteTimeSheet_Timesheet_currently_used_in_an_invoice_please_first_delete_the_invoice {
            get {
                return ResourceManager.GetString("TimeSheetRepository_DeleteTimeSheet_Timesheet_currently_used_in_an_invoice_please" +
                        "_first_delete_the_invoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Start Night Shift.
        /// </summary>
        public static string TimeStartNightShift {
            get {
                return ResourceManager.GetString("TimeStartNightShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To create report worker must be subcontractor.
        /// </summary>
        public static string To_create_report_worker_must_be_subcontractor {
            get {
                return ResourceManager.GetString("To_create_report_worker_must_be_subcontractor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Price.
        /// </summary>
        public static string UnitPrice {
            get {
                return ResourceManager.GetString("UnitPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We cannot process this operation please upgrade your subscription.
        /// </summary>
        public static string UpgradeYourSubscription {
            get {
                return ResourceManager.GetString("UpgradeYourSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You currently have an unpaid plan, please pay to make this transaction.
        /// </summary>
        public static string UserSubscribePlanUnPaid {
            get {
                return ResourceManager.GetString("UserSubscribePlanUnPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebPage.
        /// </summary>
        public static string WebPage {
            get {
                return ResourceManager.GetString("WebPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A worker with this email {0} already exists.
        /// </summary>
        public static string WorkerAlreadyExist {
            get {
                return ResourceManager.GetString("WorkerAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today&apos;s time sheet was already reported.
        /// </summary>
        public static string WorkerAlreadyReportedWorkShift {
            get {
                return ResourceManager.GetString("WorkerAlreadyReportedWorkShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///            You can not apply for this job.
        ///            This job is not available
        ///        .
        /// </summary>
        public static string WorkerCanNotApplyToJob {
            get {
                return ResourceManager.GetString("WorkerCanNotApplyToJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t report time this day please try on {0}.
        /// </summary>
        public static string WorkerCanNotRegisterTime {
            get {
                return ResourceManager.GetString("WorkerCanNotRegisterTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not update the work shift anymore.
        /// </summary>
        public static string WorkerCanNotUpdateWorkShift {
            get {
                return ResourceManager.GetString("WorkerCanNotUpdateWorkShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been rejected for this job.
        /// </summary>
        public static string WorkerHasBeenRejected {
            get {
                return ResourceManager.GetString("WorkerHasBeenRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot apply to this job because you are already booked for another job in the same shift ({0}).
        /// </summary>
        public static string WorkerIsInRequestWithSameWorkShift {
            get {
                return ResourceManager.GetString("WorkerIsInRequestWithSameWorkShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, you are not in any Order please contact your agency.
        /// </summary>
        public static string WorkerIsNotInARequest {
            get {
                return ResourceManager.GetString("WorkerIsNotInARequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You aren&apos;t approved to work.
        /// </summary>
        public static string WorkerNotApprovedToWork {
            get {
                return ResourceManager.GetString("WorkerNotApprovedToWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This worker is not available to work.
        /// </summary>
        public static string WorkerNotAvailableToWork {
            get {
                return ResourceManager.GetString("WorkerNotAvailableToWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worker not found.
        /// </summary>
        public static string WorkerNotFound {
            get {
                return ResourceManager.GetString("WorkerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string WorkerProfileNote {
            get {
                return ResourceManager.GetString("WorkerProfileNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate.
        /// </summary>
        public static string WorkerRate {
            get {
                return ResourceManager.GetString("WorkerRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your social insurance has expired on {0}.
        /// </summary>
        public static string WorkerSocialInsuranceHasExpired {
            get {
                return ResourceManager.GetString("WorkerSocialInsuranceHasExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workers Quantity.
        /// </summary>
        public static string WorkersQuantity {
            get {
                return ResourceManager.GetString("WorkersQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work shift has to have at least one element.
        /// </summary>
        public static string WorkShiftAtLeastOneElement {
            get {
                return ResourceManager.GetString("WorkShiftAtLeastOneElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This work shift can not be removed.
        /// </summary>
        public static string WorkShiftCanNotBeRemoved {
            get {
                return ResourceManager.GetString("WorkShiftCanNotBeRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work shift date time.
        /// </summary>
        public static string WorkShiftDateTime {
            get {
                return ResourceManager.GetString("WorkShiftDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must add at least {0} hours for this day {1}.
        /// </summary>
        public static string WorkShiftIncompleteHours {
            get {
                return ResourceManager.GetString("WorkShiftIncompleteHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Work Shift information is incomplete.
        /// </summary>
        public static string WorkShiftInformationIncomplete {
            get {
                return ResourceManager.GetString("WorkShiftInformationIncomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work shift must be unique {0}.
        /// </summary>
        public static string WorkShiftMustBeUnique {
            get {
                return ResourceManager.GetString("WorkShiftMustBeUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Shifts.
        /// </summary>
        public static string WorkShifts {
            get {
                return ResourceManager.GetString("WorkShifts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Shifts ({0}) must be equal to days ({1}) .
        /// </summary>
        public static string WorkShiftsError {
            get {
                return ResourceManager.GetString("WorkShiftsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wsib.
        /// </summary>
        public static string Wsib {
            get {
                return ResourceManager.GetString("Wsib", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wsib Group.
        /// </summary>
        public static string WsibGroup {
            get {
                return ResourceManager.GetString("WsibGroup", resourceCulture);
            }
        }
    }
}
